development: &default
  adapter: postgresql
  database: payements-app_development
  encoding: utf8
  min_messages: warning
  pool: 20
  timeout: 5000

test:
  <<: *default
  database: payements-app_test